spring.application.name=digi-payment-gateway
spring.profiles.active=dev
security.jwt.expiration-seconds=3600
security.jwt.refresh-expiration-seconds=1209600
security.otp.cleanup-interval-ms=60000
security.otp.resend-cooldown-seconds=45
