server.port=8080

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

# Logging
logging.level.root=INFO
logging.level.org.springframework.web=INFO
logging.level.com.digirestro.digi_payment_gateway=INFO

# JWT Secret
security.jwt.secret=${JWT_SECRET}



# PhonePe TSP Global Credentials
phonepe.tsp.client-id=${PHONEPE_TSP_CLIENT_ID}
phonepe.tsp.client-version=${PHONEPE_TSP_CLIENT_VERSION}
phonepe.tsp.client-secret=${PHONEPE_TSP_CLIENT_SECRET}
phonepe.tsp.base-url=${PHONEPE_TSP_BASE_URL}
