server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/db_digi_payment_gateway
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Logging
logging.level.root=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.com.digirestro.digi_payment_gateway=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

# JWT Secret
security.jwt.secret=dev-x629v-super-hdh2x8-secret-clbzy5-key

management.endpoints.web.exposure.include=*

# PhonePe TSP Global Credentials
phonepe.tsp.client-id=TSPDIGIRESTROUAT_2604211
phonepe.tsp.client-version=1
phonepe.tsp.client-secret=NWIzNTBhNTQtOTBiMC00NjkxLTliYWUtNzQxNjhkYjJlYjdj
phonepe.tsp.base-url=https://api-preprod.phonepe.com/apis/pg-sandbox
